name: "Merge PR into Main"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag SemVer
        uses: ./.github/actions/tag-semver
