name: "Release to Production"

on:
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Testing production"

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Deploying production"

  update-branch-main:
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fast-forward main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout main
          git merge production
          git push
