name: "Release to Production"

on:
  workflow_dispatch:
    inputs:
      merge-from:
        description: "Branch with beta features or hotfixes"
        required: true
        default: "staging"
      merge-to:
        description: "Branch to release"
        required: true
        default: "production"

permissions:
  contents: write

jobs:
  # merge branch staging into production
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge branches
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout ${{ inputs.merge-to }}
          git merge origin/${{ inputs.merge-from }}
          git push

  tag-semver:
    needs: merge
    uses: "./.github/workflows/tag-semver.yml"

  test:
    needs: tag-semver
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Testing production"

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Deploying production"

  # move branch main ahead of production
  update-branch-main:
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fast-forward main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout main
          git merge origin/production
          git push

  # move branch staging ahead of production
  update-branch-staging:
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fast-forward main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout staging
          git merge origin/production
          git push
