name: "Release to Production"

on:
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Testing production"

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Deploying production"
