name: "Pre-release to Staging"

on:
  workflow_dispatch:
    inputs:
      merge-from:
        description: "Branch with alpha features or bugfixes"
        required: true
        default: "main"
      merge-to:
        description: "Branch to pre-release"
        required: true
        default: "staging"

permissions:
  contents: write

jobs:
  # merge branch main into staging
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge branches
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout ${{ inputs.merge-to }}
          git merge origin/${{ inputs.merge-from }}
          git push

  tag-semver:
    needs: merge
    uses: "./.github/workflows/tag-semver.yml"

  test:
    needs: tag-semver
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Testing preview"

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Deploying preview"

  # move branch main ahead of staging
  update-branch-main:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fast-forward main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout main
          git merge origin/staging
          git push
